import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Listed explicitly rather than autogenerated. Every doc file has to appear
 * here: a file that builds without a sidebar entry becomes a live URL nothing
 * links to, which is indexed and read without any of its context.
 */
const sidebars: SidebarsConfig = {
  kokioSidebar: [
    {
      type: "doc",
      id: "Overview",
    },
    {
      type: "category",
      label: "Kokio",
      items: [
        {
          type: "doc",
          id: "kokio/landingIntro",
        },
        {
          type: "doc",
          id: "setup",
        },
        {
          type: "doc",
          id: "kokio/mobileApp",
        },
        {
          type: "doc",
          id: "kokio/techStack",
        },
      ],
    },
    {
      type: "category",
      label: "eSIM",
      items: [
        {
          type: "doc",
          id: "eSIM/intro",
        },
        {
          type: "doc",
          id: "eSIM/problem",
        },
        {
          type: "doc",
          id: "eSIM/solution",
        },
        {
          type: "doc",
          id: "eSIM/working",
        },
      ],
    },
    {
      type: "category",
      label: "Smart Contracts",
      items: [
        {
          type: "doc",
          id: "contracts/intro",
        },
        {
          type: "doc",
          id: "contracts/overview",
        },
        {
          type: "doc",
          id: "contracts/registry",
        },
        {
          type: "doc",
          id: "contracts/lazy-wallet-registry",
        },
        {
          type: "doc",
          id: "contracts/device-wallet-factory",
        },
        {
          type: "doc",
          id: "contracts/device-wallet",
        },
        {
          type: "doc",
          id: "contracts/esim-wallet-factory",
        },
        {
          type: "doc",
          id: "contracts/esim-wallet",
        },
        {
          type: "doc",
          id: "contracts/p256-verifier",
        },
        {
          type: "doc",
          id: "contracts/webauthn",
        },
        {
          type: "doc",
          id: "contracts/deployments",
        },
      ],
    },
    {
      type: "doc",
      id: "futureProspects",
    },
    {
      type: "doc",
      id: "resources",
    },
  ],
};

export default sidebars;
