import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Listed explicitly rather than autogenerated. Every doc file has to appear
 * here: a file that builds without a sidebar entry becomes a live URL nothing
 * links to, which is indexed and read without any of its context.
 */
const sidebars: SidebarsConfig = {
  kokioSidebar: [
    {
      type: "doc",
      id: "Overview",
    },
    {
      type: "category",
      label: "Kokio",
      items: [
        {
          type: "doc",
          id: "kokio/landingIntro",
        },
        {
          type: "doc",
          id: "setup",
        },
        {
          type: "doc",
          id: "kokio/mobileApp",
        },
        {
          type: "doc",
          id: "kokio/techStack",
        },
      ],
    },
    {
      type: "category",
      label: "eSIM",
      items: [
        {
          type: "doc",
          id: "eSIM/intro",
        },
        {
          type: "doc",
          id: "eSIM/problem",
        },
        {
          type: "doc",
          id: "eSIM/solution",
        },
        {
          type: "doc",
          id: "eSIM/working",
        },
      ],
    },
    {
      type: "category",
      label: "Smart Contracts",
      items: [
        {
          type: "doc",
          id: "contracts/intro",
        },
        {
          type: "doc",
          id: "contracts/overview",
        },
        {
          type: "doc",
          id: "contracts/registry",
        },
        {
          type: "doc",
          id: "contracts/lazy-wallet-registry",
        },
        {
          type: "doc",
          id: "contracts/device-wallet-factory",
        },
        {
          type: "doc",
          id: "contracts/device-wallet",
        },
        {
          type: "doc",
          id: "contracts/esim-wallet-factory",
        },
        {
          type: "doc",
          id: "contracts/esim-wallet",
        },
        {
          type: "doc",
          id: "contracts/p256-verifier",
        },
        {
          type: "doc",
          id: "contracts/webauthn",
        },
        {
          type: "doc",
          id: "contracts/deployments",
        },
      ],
    },
    {
      type: "category",
      label: "SDK",
      items: [
        {
          type: "doc",
          id: "sdk/overview",
        },
        {
          type: "category",
          label: "Mobile",
          items: [
            {
              type: "doc",
              id: "sdk/mobile/setup",
            },
            {
              type: "doc",
              id: "sdk/mobile/smart-account",
            },
            {
              type: "doc",
              id: "sdk/mobile/device-wallet",
            },
            {
              type: "doc",
              id: "sdk/mobile/device-wallet-factory",
            },
            {
              type: "doc",
              id: "sdk/mobile/esim-wallet",
            },
            {
              type: "doc",
              id: "sdk/mobile/registry",
            },
            {
              type: "doc",
              id: "sdk/mobile/payments",
            },
          ],
        },
        {
          type: "category",
          label: "Backend",
          items: [
            {
              type: "doc",
              id: "sdk/backend/setup",
            },
            {
              type: "doc",
              id: "sdk/backend/device-wallet",
            },
            {
              type: "doc",
              id: "sdk/backend/device-wallet-factory",
            },
            {
              type: "doc",
              id: "sdk/backend/esim-wallet",
            },
            {
              type: "doc",
              id: "sdk/backend/registry",
            },
            {
              type: "doc",
              id: "sdk/backend/lazy-wallet-registry",
            },
            {
              type: "doc",
              id: "sdk/backend/payments",
            },
            {
              type: "doc",
              id: "sdk/backend/protocol-admin",
            },
          ],
        },
      ],
    },
    {
      type: "doc",
      id: "futureProspects",
    },
    {
      type: "doc",
      id: "resources",
    },
  ],
};

export default sidebars;
